/* sigtrace: C library for generating stack traces on fault/signal
 * (https://github.com/deimonn/sigtrace) */

#ifndef _SIGTRACE_H
#define _SIGTRACE_H

/* List of signals generated by severe program faults. */
extern const int sigtrace_faults[];

/* List of signals generated by sockets, timers or by the user. */
extern const int sigtrace_unhandled[];

/* Install a handler that prints siginfo and a stack trace (when supported) for
 * each of the specified signals. The signal_list must be zero-terminated.
 *
 * Returns 0 on success. Sets errno and returns -1 on error. */
int sigtrace(const int *signal_list);

#endif
