name: Check format
on:
  pull_request:
    paths:
      - '.github/workflows/check-format.yml'
      - '.indent.pro'
      - 'check_format.sh'
      - '**.c'
      - '**.h'
  push:
    paths:
      - '.github/workflows/check-format.yml'
      - '.indent.pro'
      - 'check_format.sh'
      - '**.c'
      - '**.h'
jobs:
  check-format:
    name: Check format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install packages
        run: sudo apt install -y indent

      - name: Check format
        run: ./check_format.sh
